#!/usr/bin/env python3
"""Merge researched resources into base JSON files."""

import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1] / "MyAFBase/MyAFBase/Resources/Bases"


def normalize_resource(item: dict) -> dict:
    rid = item["id"]
    if not rid.startswith("res-"):
        item = {**item, "id": f"res-{rid}"}

    building = item.get("building")
    if building and isinstance(building, str) and building.isdigit():
        item["building"] = f"Bldg {building}"

    for key in ("hours", "description", "name", "address"):
        if key in item and isinstance(item[key], str):
            item[key] = item[key].replace("\u2013", "-").replace("\u2014", "-")

    return item


def patch_base(name: str, resources: list[dict]) -> int:
    path = BASE_DIR / f"{name}.json"
    with open(path) as f:
        data = json.load(f)
    data["resources"] = [normalize_resource(r) for r in resources]
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
    return len(data["resources"])


EGLIN = [
    {"id": "eglin-breeze-dfac", "name": "The Breeze Dining Facility (DFAC)", "category": "dining",
     "description": "Main campus-style DFAC operated by Sodexo FLY; hot meals and grab-and-go.",
     "hours": "Mon-Fri: Bfast 0630-0900, Lunch 1100-1300, Dinner 1700-1900; Sat-Sun: Bfast 0730-0830, Lunch 1100-1300, Dinner 1630-1800",
     "address": "862 West D Blvd, Eglin AFB, FL 32542", "phone": "850-882-9042",
     "url": "https://usafdining-eglin.sodexomyway.com/en-us/the-breeze", "building": "862"},
    {"id": "eglin-lift-flight-kitchen", "name": "The Lift Flight Kitchen", "category": "dining",
     "description": "Grab-and-go satellite dining for breakfast and lunch.",
     "hours": "Mon-Fri: Bfast 0600-0900, Lunch 1030-1330; Sat-Sun closed",
     "address": "60 Choctawhatchee Avenue, Eglin AFB, FL 32542", "phone": "850-882-3620",
     "url": "https://eglin96fss.com/dining/", "building": "60"},
    {"id": "eglin-legends-sports-grill", "name": "Legends Sports Grill", "category": "dining",
     "description": "Sports bar and grill; lunch and dinner; ESM meal cards accepted.",
     "hours": "See posted hours at facility",
     "address": "109 North McCarthy Avenue, Eglin AFB, FL 32542", "phone": "850-882-4728",
     "url": "https://eglin96fss.com/legends/", "building": "825"},
    {"id": "eglin-main-exchange", "name": "Eglin Main Exchange (BX)", "category": "shopping",
     "description": "Main BX with food court, barbershop, and services.",
     "hours": "Mon-Sat 0900-2000, Sun 1000-1830",
     "address": "1757 Memorial Trail, Eglin AFB, FL 32542", "phone": "850-651-5823",
     "url": "https://www.shopmyexchange.com/store-locator/eglin-main-exchange", "building": "1757"},
    {"id": "eglin-commissary", "name": "Eglin AFB Commissary", "category": "shopping",
     "description": "Defense Commissary Agency grocery; CLICK2GO curbside available.",
     "hours": "Daily 0800-1900",
     "address": "1511 Memorial Trail, Suite 1, Eglin AFB, FL 32542", "phone": "850-389-6660",
     "url": "https://shop.commissaries.com/stores/eglin-afb", "building": "1755"},
    {"id": "eglin-96th-medical-group", "name": "96th Medical Group (Eglin Hospital)", "category": "medical",
     "description": "Military treatment facility; appointments and emergency care.",
     "hours": "Appointments via central line; pharmacy and clinics have separate hours",
     "address": "307 Boatner Road, Eglin AFB, FL 32542", "phone": "850-883-8600",
     "url": "https://eglin.tricare.mil/", "building": None},
    {"id": "eglin-phoenix-fitness", "name": "Phoenix Fitness Center", "category": "fitness",
     "description": "Cardio, free weights, and plate-loaded equipment.",
     "hours": "Mon-Fri 0500-2100, Sat 0700-1700",
     "address": "404 Wicker Circle, Eglin AFB, FL 32542", "phone": "850-882-6223",
     "url": "https://eglin96fss.com/fitness/", "building": "810"},
    {"id": "eglin-field-house-fitness", "name": "Field House Fitness Center", "category": "fitness",
     "description": "Fitness center near East Gate; 24/7 access available with registration.",
     "hours": "Mon-Fri 0930-1530 manned; 24/7 registered access",
     "address": "Track & Sports Complex near East Gate, Eglin AFB, FL 32542", "phone": "850-882-6028",
     "url": "https://eglin96fss.com/field-house/", "building": "741"},
    {"id": "eglin-lightning-fitness", "name": "Lightning Fitness Center", "category": "fitness",
     "description": "33rd FW area fitness center; 24/7 access available with registration.",
     "hours": "Mon-Fri 0730-1330 manned; 24/7 registered access",
     "address": "Griffin Way, Eglin AFB, FL 32542", "phone": "850-885-3331",
     "url": "https://eglin96fss.com/fitness/lightning/", "building": "1325"},
    {"id": "eglin-mpf", "name": "Military Personnel Flight (MPF)", "category": "services",
     "description": "Personnel actions, DEERS/ID cards, assignments, promotions; walk-in ID card queue 0700-1430.",
     "hours": "See posted MPF hours; Wed training closures possible",
     "address": "310 West Van Matre Avenue, Eglin AFB, FL 32542", "phone": "850-882-6365",
     "url": "https://eglin96fss.com/mpf/", "building": "210"},
    {"id": "eglin-96fss", "name": "96th Force Support Squadron", "category": "services",
     "description": "MWR, dining, fitness, recreation, and family programs headquarters.",
     "hours": "Varies by facility",
     "address": "310 West Van Matre Avenue, Eglin AFB, FL 32542", "phone": "850-882-1110",
     "url": "https://eglin96fss.com/", "building": "210"},
    {"id": "eglin-housing-office", "name": "Housing Management Office", "category": "housing",
     "description": "Government housing assignments; privatized housing (Mayroad) co-located.",
     "hours": "Mon-Fri business hours",
     "address": "2950 Azalea Drive, Eglin AFB, FL 32542", "phone": "850-882-4533",
     "url": "https://www.housing.af.mil/Home/Installations/Elgin-AFB/", "building": "38499"},
    {"id": "eglin-fcu", "name": "Eglin Federal Credit Union", "category": "finance",
     "description": "On-base full-service credit union branch.",
     "hours": "Mon-Thu 0900-1700; Fri 0900-1700; Sat-Sun closed",
     "address": "601 E Eglin Blvd, Eglin AFB, FL 32542", "phone": "850-862-0111",
     "url": "https://www.eglinfcu.org/", "building": None},
    {"id": "eglin-pool", "name": "Eglin Pool", "category": "recreation",
     "description": "Seasonal outdoor pool next to Phoenix Fitness Center; free admission.",
     "hours": "Thu-Sun 1000-1700 summer season; Mon-Wed closed",
     "address": "404 Wicker Circle area, Eglin AFB, FL 32542", "phone": "850-883-1244",
     "url": "https://eglin96fss.com/pool/", "building": "812"},
    {"id": "eglin-bayview", "name": "Bayview Community Center", "category": "recreation",
     "description": "Waterfront event center on Choctawhatchee Bay; bingo, weddings, unit events.",
     "hours": "See posted hours; bingo Wed evenings",
     "address": "1018 Boatner Road, Eglin AFB, FL 32542", "phone": "850-882-4766",
     "url": "https://eglin96fss.com/bayview/", "building": "10870"},
    {"id": "eglin-outdoor-rec", "name": "Outdoor Recreation", "category": "recreation",
     "description": "Equipment rental, trips, FamCamp, and recreation programs.",
     "hours": "Mon-Fri business hours",
     "address": "Flagler Road, Eglin AFB, FL 32542", "phone": "850-882-5058",
     "url": "https://eglin96fss.com/outdoorrec/", "building": "732"},
    {"id": "eglin-itt", "name": "Information, Tickets & Travel (ITT)", "category": "recreation",
     "description": "Discount tickets, tours, and leisure travel agency.",
     "hours": "Mon-Fri 0900-1600, Sat 0900-1400; closed Sun and federal holidays",
     "address": "1760 Memorial Trail, Eglin AFB, FL 32542", "phone": "850-882-5930",
     "url": "https://eglin96fss.com/itt/", "building": "1760"},
    {"id": "eglin-visitor-control-center", "name": "Visitor Control Center", "category": "safety",
     "description": "Visitor passes and pass & registration at Air Force Armament Museum campus.",
     "hours": "Daily 0600-2200 VCC; pass pickup weekdays 0700-1600, weekends 0800-1200",
     "address": "100 Museum Drive, Eglin AFB, FL 32542", "phone": "850-883-0948",
     "url": "https://www.eglin.af.mil/About-Us/Fact-Sheets/Display/Article/3886337/eglin-visitor-control-center/",
     "building": "2938"},
]

TRAVIS = [
    {"id": "travis-monarch-dfac", "name": "Monarch Dining Facility (DFAC)", "category": "dining",
     "description": "Main DFAC operated by Aramark; open to all with base access.",
     "hours": "Bfast Mon-Fri 0600-0900, Sat-Sun 0630-0830; Lunch daily 1100-1330; Dinner daily 1630-1930",
     "address": "600 Burgan Blvd, Travis AFB, CA 94535", "phone": "707-424-0906",
     "url": "https://travisfss.com/monarch-dining-facility/", "building": "1301"},
    {"id": "travis-all-night-cafe", "name": "All Night Cafe", "category": "dining",
     "description": "24/7 grab-and-go kiosk in Hangar 810 near the flight line.",
     "hours": "Open 24/7",
     "address": "Ragsdale Street, Hangar 810, Travis AFB, CA 94535", "phone": "707-424-6502",
     "url": "https://travisfss.com/allnightcafe/", "building": "810"},
    {"id": "travis-flight-kitchen", "name": "Flight Kitchen", "category": "dining",
     "description": "24-hour boxed meals for mission-essential personnel.",
     "hours": "Open 24 hours",
     "address": "600 Burgan Blvd, Travis AFB, CA 94535", "phone": "707-424-5675",
     "url": "https://travisfss.com/flight-kitchen/", "building": "1301"},
    {"id": "travis-wingmans", "name": "Wingman's (DBCC Restaurant)", "category": "dining",
     "description": "Sports bar and restaurant inside Delta Breeze Community Center.",
     "hours": "See posted hours at facility",
     "address": "400 Windward Drive, Travis AFB, CA 94535", "phone": "707-424-0032",
     "url": "https://travisfss.com/dbcc/", "building": "400"},
    {"id": "travis-main-exchange", "name": "Travis Main Exchange (BX)", "category": "shopping",
     "description": "Large main BX with food court and mini mall.",
     "hours": "Mon 0930-1930; Tue-Sat 0900-2000; Sun 1000-1800",
     "address": "461 Skymaster Circle, Travis AFB, CA 94535", "phone": "707-437-4633",
     "url": "https://www.shopmyexchange.com/store-locator/travis-afb-main-exchange", "building": "648"},
    {"id": "travis-commissary", "name": "Travis AFB Commissary", "category": "shopping",
     "description": "Defense Commissary Agency grocery; CLICK2GO available.",
     "hours": "Daily 0900-1900",
     "address": "460 Skymaster Drive, Travis AFB, CA 94535", "phone": "707-639-5830",
     "url": "https://shop.commissaries.com/stores/travis-afb", "building": None},
    {"id": "travis-dgmc", "name": "David Grant USAF Medical Center", "category": "medical",
     "description": "Regional military treatment facility and 60th Medical Group headquarters.",
     "hours": "Appointments via central line; clinics vary",
     "address": "101 Bodin Circle, Travis AFB, CA 94535", "phone": "707-423-3000",
     "url": "https://travis.tricare.mil/", "building": "777"},
    {"id": "travis-fitness-center", "name": "Travis Fitness Center", "category": "fitness",
     "description": "Main fitness center with classes and 24/7 CAC access.",
     "hours": "See FSS site; 24/7 access with registration",
     "address": "550 Travis Avenue, Travis AFB, CA 94535", "phone": "707-424-2008",
     "url": "https://travisfss.com/fitness-center/", "building": "434"},
    {"id": "travis-nose-dock-gym", "name": "Nose Dock Gym", "category": "fitness",
     "description": "Secondary gym in Hangar 844.",
     "hours": "See FSS fitness page",
     "address": "Hangar 844, Goodall Street, Travis AFB, CA 94535", "phone": "707-424-2007",
     "url": "https://travisfss.com/fitness-center/", "building": "844"},
    {"id": "travis-mpf", "name": "Military Personnel Flight (MPF)", "category": "services",
     "description": "Personnel actions and DEERS/ID card services.",
     "hours": "See posted hours on FSS site",
     "address": "540 Airlift Drive, D Wing, Travis AFB, CA 94535", "phone": "707-424-8480",
     "url": "https://travisfss.com/military-personnel-flight/", "building": "381"},
    {"id": "travis-60fss", "name": "60th Force Support Squadron", "category": "services",
     "description": "MWR, dining, fitness, recreation, and family programs.",
     "hours": "Varies by facility",
     "address": "540 Airlift Circle, F Wing Room F100, Travis AFB, CA 94535", "phone": "707-424-5470",
     "url": "https://travisfss.com/", "building": "381"},
    {"id": "travis-housing-office", "name": "Housing Management Office", "category": "housing",
     "description": "Government and unaccompanied housing assistance.",
     "hours": "Mon-Fri business hours",
     "address": "344 Hangar Avenue, Travis AFB, CA 94535", "phone": "707-424-1746",
     "url": "https://www.housing.af.mil/Home/Installations/Travis-AFB/", "building": "576"},
    {"id": "travis-armed-forces-bank", "name": "Armed Forces Bank", "category": "finance",
     "description": "On-base military bank branch.",
     "hours": "Mon-Thu 0900-1700, Fri 0900-1800",
     "address": "350 Hickam Avenue, Travis AFB, CA 94535", "phone": "707-437-3091",
     "url": "https://www.afbank.com/", "building": None},
    {"id": "travis-credit-union", "name": "Travis Credit Union", "category": "finance",
     "description": "On-base credit union branch.",
     "hours": "Mon-Fri 0900-1630, Sat 1000-1400",
     "address": "659 Skymaster Drive, Travis AFB, CA 94535", "phone": "707-449-4000",
     "url": "https://www.traviscu.org/locations/travis-branch/", "building": None},
    {"id": "travis-bowl", "name": "Travis Bowl", "category": "recreation",
     "description": "32-lane bowling center with pro shop.",
     "hours": "Mon-Thu 1100-2100, Fri-Sat 1100-2200, Sun 1200-1800",
     "address": "571 Travis Avenue, Travis AFB, CA 94535", "phone": "707-437-4737",
     "url": "https://travisfss.com/travis-bowl/", "building": "214"},
    {"id": "travis-cypress-lakes-golf", "name": "Cypress Lakes Golf Course", "category": "recreation",
     "description": "Par-72 course open to authorized patrons.",
     "hours": "Daily 0630-1700",
     "address": "5601 Meridian Road, Travis AFB, CA 94535", "phone": "707-448-7186",
     "url": "https://travisfss.com/cypress-lakes-golf-course/", "building": "2012"},
    {"id": "travis-aquatic-center", "name": "Travis Aquatic Center", "category": "recreation",
     "description": "Seasonal base pool with lap lanes and slides.",
     "hours": "Memorial Day-Labor Day; call to verify",
     "address": "Waldron Street, Travis AFB, CA 94535", "phone": "707-424-5283",
     "url": "https://travisfss.com/travis-aquatic-center/", "building": "232"},
    {"id": "travis-dbcc", "name": "Delta Breeze Community Center", "category": "recreation",
     "description": "Event center with ballrooms and community nights.",
     "hours": "See posted hours on FSS site",
     "address": "400 Windward Drive, Travis AFB, CA 94535", "phone": "707-424-0032",
     "url": "https://travisfss.com/dbcc/", "building": "400"},
    {"id": "travis-odr", "name": "Outdoor Recreation", "category": "recreation",
     "description": "Equipment rental, trips, and FamCamp.",
     "hours": "Mon-Fri business hours",
     "address": "273 Ellis Drive, Travis AFB, CA 94535", "phone": "707-424-0969",
     "url": "https://travisfss.com/odr/", "building": "863"},
    {"id": "travis-visitor-center", "name": "Visitor Control Center", "category": "safety",
     "description": "Day visitor passes; sponsor required; REAL ID required.",
     "hours": "Mon-Fri 0600-1800, Sat-Sun 0800-1600",
     "address": "Air Base Parkway, Travis AFB, CA 94535", "phone": "707-424-1462",
     "url": "https://www.travis.af.mil/Contact-Us/Questions/", "building": None},
    {"id": "travis-pass-registration", "name": "Pass & Registration", "category": "safety",
     "description": "Long-term passes and foreign national vetting.",
     "hours": "Mon-Fri 0800-1600",
     "address": "540 Airlift Drive, C Wing, Travis AFB, CA 94535", "phone": "707-424-6736",
     "url": "https://www.travis.af.mil/Contact-Us/Questions/", "building": "381"},
]

LACKLAND = [
    {"id": "lackland-amigo-dfac", "name": "Amigo Dining Facility", "category": "dining",
     "description": "Primary dining facility for permanent party and eligible patrons.",
     "hours": "Mon-Fri: Breakfast 0600-0800, Lunch 1100-1300, Dinner 1700-1900; Sat-Sun/Holidays: Breakfast 0730-0900, Lunch 1130-1330, Dinner 1700-1830",
     "address": "JBSA Lackland, TX 78236", "phone": "210-671-5112",
     "url": "https://www.jbsa.mil/Information/Dining-Facility/", "building": "Bldg 7532"},
    {"id": "lackland-mesquite-dfac", "name": "Mesquite Dining Facility", "category": "dining",
     "description": "Dining facility serving Lackland training populations.",
     "hours": "Mon-Fri: Breakfast 0500-0700, Lunch 1100-1300, Dinner 1700-1900; Sun: Breakfast 0700-0830, Lunch 1100-1230, Dinner 1700-1830",
     "address": "JBSA Lackland, TX 78236", "phone": "210-671-1939",
     "url": "https://www.jbsa.mil/Information/Dining-Facility/", "building": "Bldg 10175"},
    {"id": "lackland-live-oak-dfac", "name": "Live Oak Dining Facility", "category": "dining",
     "description": "Dining facility serving Lackland. Use Mesquite DFAC on Sundays.",
     "hours": "Mon-Fri: Breakfast 0530-0730, Lunch 1045-1245, Dinner 1700-1900; Sat/Holidays: Breakfast 0700-0830, Lunch 1100-1230, Dinner 1700-1830",
     "address": "JBSA Lackland, TX 78236", "phone": "210-671-4827",
     "url": "https://www.jbsa.mil/Information/Dining-Facility/", "building": "Bldg 10810"},
    {"id": "lackland-main-exchange", "name": "JBSA-Lackland Main Exchange", "category": "shopping",
     "description": "Main BX with retail, food court, barber, optical, and gas station.",
     "hours": "Mon-Sat 0830-2100; Sun 0900-1930",
     "address": "2180 Reese Street, JBSA Lackland, TX 78236", "phone": "210-674-6465",
     "url": "https://www.shopmyexchange.com/store-locator/jbsa-lackland-main-exchange", "building": "Bldg 1385"},
    {"id": "lackland-commissary", "name": "Lackland Commissary", "category": "shopping",
     "description": "Defense Commissary Agency grocery store with CLICK2GO.",
     "hours": "Sun 0730-1800; Mon-Fri 0730-2000; Sat 0730-1800",
     "address": "2250 Foulois Street, Bldg 8400, JBSA Lackland, TX 78236-1039", "phone": "210-276-2119",
     "url": "https://shop.commissaries.com/stores/lackland", "building": "Bldg 8400"},
    {"id": "lackland-wilford-hall", "name": "Wilford Hall Ambulatory Surgical Center", "category": "medical",
     "description": "59th Medical Wing outpatient MTF. 24/7 acute care clinic.",
     "hours": "24/7 acute care; clinics Mon-Fri 0730-1630",
     "address": "2200 Bergquist Drive, Ste 1, JBSA Lackland, TX 78236-9908", "phone": "210-292-7412",
     "url": "https://wilfordhall.tricare.mil/", "building": "Bldg 4550"},
    {"id": "lackland-chaparral-fitness", "name": "Chaparral Fitness Center", "category": "fitness",
     "description": "502 FSS fitness center with 24/7 CAC access after in-person registration.",
     "hours": "24/7 access available with registered CAC",
     "address": "JBSA Lackland, TX 78236", "phone": "210-671-2401",
     "url": "https://www.jbsa.mil/", "building": "Bldg 7346"},
    {"id": "lackland-gateway-fitness", "name": "Gateway Fitness Center", "category": "fitness",
     "description": "502 FSS fitness center for cardio, weights, courts, and group exercise.",
     "hours": "Contact facility for current hours",
     "address": "JBSA Lackland, TX 78236", "phone": "210-671-1348",
     "url": "https://www.jbsa.mil/", "building": "Bldg 10330"},
    {"id": "lackland-warhawk-fitness", "name": "Warhawk Fitness Center", "category": "fitness",
     "description": "502 FSS fitness center including pool access at Warhawk Pool.",
     "hours": "Contact facility for current hours",
     "address": "JBSA Lackland, TX 78236", "phone": "210-671-2016",
     "url": "https://www.jbsa.mil/", "building": "Bldg 2418"},
    {"id": "lackland-mpf", "name": "802d Military Personnel Flight (Lackland MPS)", "category": "services",
     "description": "ID cards, in-/out-processing, assignments, promotions, and DEERS updates.",
     "hours": "Mon-Thu 0730-1500; Fri 0730-1200",
     "address": "JBSA Lackland, TX 78236", "phone": "210-671-6006",
     "url": "https://www.jbsa.mil/Resources/802mpf/", "building": "Bldg 5616"},
    {"id": "lackland-housing-office", "name": "JBSA-Lackland Housing Office", "category": "housing",
     "description": "On-base family and unaccompanied housing assistance and referrals.",
     "hours": "Mon-Fri 0730-1630",
     "address": "JBSA Lackland, TX 78236", "phone": "210-671-1840",
     "url": "https://www.jbsa.mil/Housing/", "building": "Bldg 1524"},
    {"id": "lackland-mfrc", "name": "Military & Family Readiness Center", "category": "services",
     "description": "Deployment support, relocation, financial readiness, and family programs.",
     "hours": "Mon-Fri during duty hours",
     "address": "2160 Kenly Avenue, JBSA Lackland, TX 78236", "phone": "210-671-3722",
     "url": "https://www.jbsa.mil/", "building": "Bldg 1249"},
    {"id": "lackland-finance-office", "name": "502 CPTS Finance Customer Service", "category": "finance",
     "description": "Military pay, travel vouchers, and finance customer service.",
     "hours": "Mon-Fri during duty hours",
     "address": "JBSA Lackland, TX 78236", "phone": "210-671-1851",
     "url": "https://www.jbsa.mil/", "building": "Bldg 5616"},
    {"id": "lackland-gateway-hills-golf", "name": "Gateway Hills Golf Course", "category": "recreation",
     "description": "18-hole golf course with pro shop.",
     "hours": "Contact pro shop for tee times and hours",
     "address": "JBSA Lackland, TX 78236", "phone": "210-671-3466",
     "url": "https://www.jbsa.mil/", "building": "Bldg 2901"},
    {"id": "lackland-skylark-bowling", "name": "Skylark Bowling Center", "category": "recreation",
     "description": "Bowling, arcade, and snack bar.",
     "hours": "Contact facility for current hours",
     "address": "JBSA Lackland, TX 78236", "phone": "210-671-1234",
     "url": "https://www.jbsa.mil/", "building": "Bldg 6476"},
    {"id": "lackland-skylark-pool", "name": "Skylark Aquatics Center", "category": "recreation",
     "description": "Outdoor pool and aquatics programs.",
     "hours": "Seasonal; contact for schedule",
     "address": "JBSA Lackland, TX 78236", "phone": "210-671-3780",
     "url": "https://www.jbsa.mil/", "building": "Bldg 6482"},
    {"id": "lackland-itt", "name": "Information, Tickets & Travel", "category": "recreation",
     "description": "Discount tickets, leisure travel, and MWR trip planning.",
     "hours": "Mon-Fri during duty hours",
     "address": "JBSA Lackland, TX 78236", "phone": "210-671-3059",
     "url": "https://www.jbsa.mil/", "building": "Bldg 5506"},
    {"id": "lackland-visitor-center", "name": "Valley High Visitor Center", "category": "safety",
     "description": "Visitor Control Center for short- and long-term base access passes.",
     "hours": "Contact VCC for current gate and visitor hours",
     "address": "JBSA Lackland, TX 78236", "phone": "210-671-1457",
     "url": "https://www.jbsa.mil/Home/VisitorInformation.aspx", "building": "Bldg 9504"},
    {"id": "lackland-security-forces", "name": "802d Security Forces Squadron", "category": "safety",
     "description": "Base defense, law enforcement, and pass & registration.",
     "hours": "24/7 emergency response",
     "address": "JBSA Lackland, TX 78236", "phone": "210-671-2018",
     "url": "https://www.jbsa.mil/", "building": "Bldg 1030"},
]

RANDOLPH = [
    {"id": "randolph-wingman-cafe", "name": "Wingman Cafe Dining Facility", "category": "dining",
     "description": "Primary DFAC at JBSA-Randolph (formerly Rendezvous DFAC).",
     "hours": "Mon-Fri: Breakfast 0600-0900, Lunch 1030-1330, Dinner 1630-1830; Sat-Sun: Breakfast 0730-0830, Brunch 1030-1330, Dinner 1630-1800",
     "address": "1985 1st Street West, Universal City, TX 78150", "phone": "210-652-5533",
     "url": "https://www.jbsa.mil/Information/Dining-Facility/", "building": "Bldg 860"},
    {"id": "randolph-main-exchange", "name": "JBSA-Randolph Main Exchange", "category": "shopping",
     "description": "Main BX with retail, food court, barber, optical, and gas station.",
     "hours": "Mon-Fri 0830-2030; Sat 0900-1900; Sun 0900-1900",
     "address": "630 3rd Street West, JBSA Randolph, TX 78150", "phone": "210-658-7471",
     "url": "https://www.shopmyexchange.com/store-locator/jbsa-randolph-main-exchange", "building": "Bldg 1068"},
    {"id": "randolph-commissary", "name": "Randolph Commissary", "category": "shopping",
     "description": "Defense Commissary Agency grocery store with CLICK2GO.",
     "hours": "Sun 0900-1800; Mon-Fri 0900-2000; Sat 0800-1900",
     "address": "770 3rd Street West, Bldg 1075, Randolph AFB, TX 78150", "phone": "210-451-4212",
     "url": "https://shop.commissaries.com/stores/randolph-afb", "building": "Bldg 1075"},
    {"id": "randolph-clinic", "name": "JBSA-Randolph Clinic", "category": "medical",
     "description": "359th Medical Group outpatient clinic for eligible beneficiaries.",
     "hours": "Mon-Fri 0730-1630",
     "address": "221 3rd Street West, Bldg 1040, JBSA Randolph, TX 78150", "phone": "210-652-6403",
     "url": "https://randolph.tricare.mil/", "building": "Bldg 1040"},
    {"id": "randolph-rambler-fitness", "name": "Rambler Fitness Center", "category": "fitness",
     "description": "502 FSS fitness center with indoor track, courts, and 24/7 CAC access.",
     "hours": "Mon-Fri 0500-2100; Sat-Sun 0900-1700; 24/7 CAC access available",
     "address": "JBSA Randolph, TX 78150", "phone": "210-652-7263",
     "url": "https://www.jbsa.mil/", "building": "Bldg 999"},
    {"id": "randolph-mpf", "name": "802d Military Personnel Flight (Randolph MPS)", "category": "services",
     "description": "ID cards, customer support, assignments, promotions, and retirements.",
     "hours": "Mon-Thu 0730-1500; Fri 0730-1200",
     "address": "550 D Street East, JBSA Randolph, TX 78148", "phone": "210-652-3036",
     "url": "https://www.jbsa.mil/Resources/802d-Military-Personnel-Flight/Randolph-MPS/", "building": "Bldg 399"},
    {"id": "randolph-housing-office", "name": "JBSA-Randolph Housing Office", "category": "housing",
     "description": "Family and unaccompanied housing applications and referrals.",
     "hours": "Mon-Fri 0800-1600",
     "address": "JBSA Randolph, TX 78150", "phone": "210-652-1840",
     "url": "https://www.jbsa.mil/Housing/", "building": "Bldg 144"},
    {"id": "randolph-mfrc", "name": "Military & Family Readiness Center", "category": "services",
     "description": "Relocation, deployment, financial readiness, and family support programs.",
     "hours": "Mon-Fri during duty hours",
     "address": "JBSA Randolph, TX 78150", "phone": "210-652-5321",
     "url": "https://www.jbsa.mil/", "building": "Bldg 693"},
    {"id": "randolph-finance-office", "name": "502 CPTS Finance (Randolph)", "category": "finance",
     "description": "Military pay and finance customer service for Randolph-area units.",
     "hours": "Mon-Fri during duty hours",
     "address": "JBSA Randolph, TX 78150", "phone": "210-652-0132",
     "url": "https://www.jbsa.mil/", "building": "Bldg 399"},
    {"id": "randolph-oaks-golf", "name": "Randolph Oaks Golf Course", "category": "recreation",
     "description": "Golf course with Mulligan's Grill and pro shop.",
     "hours": "Contact pro shop for tee times",
     "address": "JBSA Randolph, TX 78150", "phone": "210-652-4653",
     "url": "https://www.jbsa.mil/", "building": "Bldg 1300"},
    {"id": "randolph-bowling", "name": "Randolph Bowling Center", "category": "recreation",
     "description": "Bowling center with Sparetime Grill.",
     "hours": "Contact facility for current hours",
     "address": "JBSA Randolph, TX 78150", "phone": "210-652-6271",
     "url": "https://www.jbsa.mil/", "building": "Bldg 870"},
    {"id": "randolph-center-pool", "name": "Center Pool", "category": "recreation",
     "description": "Outdoor aquatics center.",
     "hours": "Seasonal; contact for schedule",
     "address": "JBSA Randolph, TX 78150", "phone": "210-652-2060",
     "url": "https://www.jbsa.mil/", "building": "Bldg 502"},
    {"id": "randolph-itt", "name": "Information, Tickets & Travel", "category": "recreation",
     "description": "Discount tickets, travel, and MWR programs.",
     "hours": "Mon-Fri during duty hours",
     "address": "JBSA Randolph, TX 78150", "phone": "210-652-5142",
     "url": "https://www.jbsa.mil/", "building": "Bldg 895"},
    {"id": "randolph-visitor-control", "name": "Visitor Control Center", "category": "safety",
     "description": "Issues visitor passes. Randolph visitors must provide proof of auto insurance.",
     "hours": "See jbsa.mil visitor information for gate hours",
     "address": "JBSA Randolph, TX 78150", "phone": "210-652-3584",
     "url": "https://www.jbsa.mil/Home/VisitorInformation.aspx", "building": "Bldg 1032"},
    {"id": "randolph-security-forces", "name": "902d Security Forces Squadron", "category": "safety",
     "description": "Base defense and law enforcement.",
     "hours": "24/7 emergency response",
     "address": "JBSA Randolph, TX 78150", "phone": "210-652-5700",
     "url": "https://www.jbsa.mil/", "building": "Bldg 235"},
]

SHEPPARD = [
    {"id": "sheppard-sagebrush-dfac", "name": "Sagebrush Dining Facility", "category": "dining",
     "description": "DFAC serving Sheppard AFB eligible patrons.",
     "hours": "See monthly menu at 82fss.com for current meal periods",
     "address": "726 Avenue J, Bldg 1320, Sheppard AFB, TX 76311", "phone": "940-855-5590",
     "url": "https://82fss.com/dining-facilities/", "building": "Bldg 1320"},
    {"id": "sheppard-tumbleweed-dfac", "name": "Tumbleweed Dining Facility", "category": "dining",
     "description": "DFAC open to all base populations including Airmen in Training.",
     "hours": "See monthly menu at 82fss.com for current meal periods",
     "address": "909 5th Avenue, Bldg 1368, Sheppard AFB, TX 76311", "phone": "940-855-3351",
     "url": "https://82fss.com/dining-facilities/", "building": "Bldg 1368"},
    {"id": "sheppard-mesquite-dfac", "name": "Mesquite Dining Facility", "category": "dining",
     "description": "DFAC serving Sheppard training and permanent party.",
     "hours": "See monthly menu at 82fss.com for current meal periods",
     "address": "831 Avenue F, Bldg 805, Sheppard AFB, TX 76311", "phone": "940-851-7757",
     "url": "https://82fss.com/dining-facilities/", "building": "Bldg 805"},
    {"id": "sheppard-main-exchange", "name": "Sheppard AFB Main Exchange", "category": "shopping",
     "description": "Main BX with retail, food court, barber, optical, and gas station.",
     "hours": "Mon-Sat 0900-2000; Sun 1000-1800",
     "address": "220 Community Circle Drive, Bldg 239, Sheppard AFB, TX 76311", "phone": "940-855-4318",
     "url": "https://www.shopmyexchange.com/", "building": "Bldg 239"},
    {"id": "sheppard-commissary", "name": "Sheppard AFB Commissary", "category": "shopping",
     "description": "Defense Commissary Agency grocery store with CLICK2GO.",
     "hours": "Sun 1100-1700; Mon-Fri 0830-1900; Sat 0830-1800",
     "address": "130 Community Center Drive, Bldg 120, Sheppard AFB, TX 76311", "phone": "940-676-2901",
     "url": "https://shop.commissaries.com/stores/sheppard-afb", "building": "Bldg 120"},
    {"id": "sheppard-medical-clinic", "name": "Sheppard AFB Medical Clinic", "category": "medical",
     "description": "82nd Medical Group outpatient clinic.",
     "hours": "Mon-Fri 0730-1630",
     "address": "149 Hart Street, Bldg 1200, Sheppard AFB, TX 76311", "phone": "940-676-1847",
     "url": "https://www.sheppard.af.mil/", "building": "Bldg 1200"},
    {"id": "sheppard-levitow-fitness", "name": "Levitow Fitness Center", "category": "fitness",
     "description": "Permanent-party fitness center with 24-hour CAC access.",
     "hours": "24-hour access for registered eligible cardholders",
     "address": "825 3rd Avenue, Bldg 384, Sheppard AFB, TX 76311", "phone": "940-676-2972",
     "url": "https://82fss.com/fitness-centers/", "building": "Bldg 384"},
    {"id": "sheppard-pitsenbarger-fitness", "name": "Pitsenbarger Fitness Center", "category": "fitness",
     "description": "Fitness center open to all populations including Airmen in Training.",
     "hours": "24-hour access for eligible cardholders",
     "address": "511 Avenue H, Bldg 540, Sheppard AFB, TX 76311", "phone": "940-676-0491",
     "url": "https://82fss.com/fitness-centers/", "building": "Bldg 540"},
    {"id": "sheppard-mpf", "name": "Military Personnel Flight", "category": "services",
     "description": "ID cards, in-processing, assignments, promotions, and retirements.",
     "hours": "Mon-Fri during duty hours; use RAPIDS for ID card appointments",
     "address": "426 Tuskegee Airmen Avenue, Bldg 402 Room 125, Sheppard AFB, TX 76311", "phone": "940-676-4314",
     "url": "https://82fss.com/military-personnel-flight/", "building": "Bldg 402"},
    {"id": "sheppard-housing-office", "name": "Military Housing Office", "category": "housing",
     "description": "Family housing waitlist and privatized housing (Balfour Beatty Communities).",
     "hours": "Mon 0730-1500; Tue-Fri 0730-1600",
     "address": "310 H Avenue, Bldg 373, Sheppard AFB, TX 76311", "phone": "940-676-1840",
     "url": "https://www.housing.af.mil/Home/Installations/Sheppard-AFB/", "building": "Bldg 373"},
    {"id": "sheppard-mfrc", "name": "Military & Family Readiness Center", "category": "services",
     "description": "Relocation, TAP, financial readiness, EFMP, and family support.",
     "hours": "Mon-Fri during duty hours",
     "address": "709 9th Street, Bldg 960, Sheppard AFB, TX 76311", "phone": "940-676-4358",
     "url": "https://82fss.com/military-family-readiness-center/", "building": "Bldg 960"},
    {"id": "sheppard-finance", "name": "82nd Comptroller Squadron (Finance)", "category": "finance",
     "description": "Military pay and finance customer service.",
     "hours": "Mon-Fri during duty hours",
     "address": "426 Tuskegee Airmen Avenue, Sheppard AFB, TX 76311", "phone": "940-676-4314",
     "url": "https://www.sheppard.af.mil/", "building": "Bldg 402"},
    {"id": "sheppard-runway-bar-grill", "name": "Runway Bar & Grill", "category": "recreation",
     "description": "Bar and grill with game room, patio, and full bar.",
     "hours": "Contact facility for current hours",
     "address": "900 1st Avenue, Bldg 4490, Sheppard AFB, TX 76311", "phone": "940-676-3175",
     "url": "https://82fss.com/runway-bar-grill/", "building": "Bldg 4490"},
    {"id": "sheppard-outdoor-recreation", "name": "Outdoor Recreation", "category": "recreation",
     "description": "Equipment rental, camping, and outdoor adventure programs.",
     "hours": "Mon-Fri during duty hours",
     "address": "Sheppard AFB, TX 76311", "phone": "940-676-4141",
     "url": "https://82fss.com/", "building": None},
    {"id": "sheppard-bunker-hill-pool", "name": "Bunker Hill Pool", "category": "recreation",
     "description": "Outdoor aquatics facility.",
     "hours": "Seasonal; contact Outdoor Recreation",
     "address": "202 Skaggs Drive, Bldg 1125, Sheppard AFB, TX 76311", "phone": "940-676-4141",
     "url": "https://82fss.com/", "building": "Bldg 1125"},
    {"id": "sheppard-visitor-center", "name": "Visitor Control Center", "category": "safety",
     "description": "Issues temporary vehicle and visitor passes at Missile Road Gate.",
     "hours": "Mon-Fri 0630-1700",
     "address": "State Route 240 and Missile Road, Bldg 1405, Sheppard AFB, TX 76311", "phone": "940-676-7441",
     "url": "https://www.sheppard.af.mil/Newcomers/Technical-Training-Students/", "building": "Bldg 1405"},
    {"id": "sheppard-security-forces", "name": "Base Defense Operations Center", "category": "safety",
     "description": "Security Forces operations and emergencies.",
     "hours": "24/7",
     "address": "Sheppard AFB, TX 76311", "phone": "940-676-2982",
     "url": "https://www.sheppard.af.mil/", "building": None},
]

PATCHES = {
    "eglin": EGLIN,
    "travis": TRAVIS,
    "lackland": LACKLAND,
    "randolph": RANDOLPH,
    "sheppard": SHEPPARD,
}

if __name__ == "__main__":
    for name, resources in PATCHES.items():
        count = patch_base(name, resources)
        cats = sorted({r["category"] for r in resources})
        print(f"{name}: {count} resources, categories: {', '.join(cats)}")
